version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulateur
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0  # Ajout de cette ligne
    restart: unless-stopped