version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulateur
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.venv
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge